import java.sql.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.text.DateFormat;
import java.time.LocalDateTime;
import java.text.SimpleDateFormat;
import javax.swing.*;
import net.proteanit.sql.DbUtils;
import java.sql.*;
import javax.swing.table.*;
import javax.swing.*;
//import java.lang.Math;
import java.math.*;
import java.util.Date;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author RODGER
 */

public class stock_view4 extends javax.swing.JFrame {

    /**
     * Creates new form add_stock
     */
    public stock_view4() {
        initComponents();
        try{
           javaconnect connect=new javaconnect();
          Connection conn=javaconnect.getConnection();
        //Connection conn=null;
        ResultSet rs=null;
        Statement stmt=null;
        PreparedStatement pst=null;
        
        String sql="select  id as 'id',`Date_added` as 'Date added',name as 'Name',detail as 'Description',quantity as 'Quantity',buying_price as 'Buying price',supplier as 'Supplier',price as 'Cost (Ksh)' from product order by date_added desc";
       pst=conn.prepareStatement(sql);
        rs=pst.executeQuery();
        jTable1.setModel(DbUtils.resultSetToTableModel(rs));
                TableColumnModel tcm=jTable1.getColumnModel();
        tcm.removeColumn(tcm.getColumn(0));
       DateFormat dtf=new SimpleDateFormat("yyyy-MM-dd");
       Date date=new Date();
      // java.util.Date date=new java.util.Date();
        dtf.format(date);
        sell_date.setDate(date);
String sql2="select id,name,detail,quantity,total_cost,profit,date_sold,sold_by from sells where date_sold like '%"+dtf.format(date)+"%' order by date_sold desc";
 
        //String sql2="select * from sells";
         pst=conn.prepareStatement(sql2);
        rs=pst.executeQuery();
        t_sold.setModel(DbUtils.resultSetToTableModel(rs));
        TableColumnModel tcm2=t_sold.getColumnModel();
        tcm2.removeColumn(tcm2.getColumn(0));
        
        }
        catch(Exception e){
        JOptionPane.showMessageDialog(null,e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        search = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        supplier = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        detail = new javax.swing.JTextField();
        price_2 = new javax.swing.JTextField();
        quantity_2 = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        buy_price_2 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        buy_price2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        profit = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        avg_buy = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        t_sold = new javax.swing.JTable();
        sell_date = new com.toedter.calendar.JDateChooser();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 153, 255));

        search.setBackground(new java.awt.Color(153, 204, 255));
        search.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        search.setForeground(new java.awt.Color(255, 255, 255));
        search.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255), 3));
        search.setSelectedTextColor(new java.awt.Color(0, 51, 51));
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchKeyReleased(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Search");

        jComboBox1.setBackground(new java.awt.Color(153, 204, 255));
        jComboBox1.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Name", "Detail", "Supplier", "Date_added" }));
        jComboBox1.setToolTipText("Search Field (Column)");
        jComboBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox1MouseClicked(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 143, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        supplier.setBackground(new java.awt.Color(163, 204, 255));
        supplier.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        supplier.setForeground(new java.awt.Color(255, 255, 255));
        supplier.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255), 3));
        jPanel1.add(supplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 280, 40));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("DESCRIPTION");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("QUANTITY");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("SUPPLIER");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        detail.setBackground(new java.awt.Color(153, 204, 255));
        detail.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        detail.setForeground(new java.awt.Color(255, 255, 255));
        detail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255), 3));
        detail.setEnabled(false);
        jPanel1.add(detail, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 280, 40));

        price_2.setBackground(new java.awt.Color(153, 204, 255));
        price_2.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        price_2.setForeground(new java.awt.Color(255, 255, 255));
        price_2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255), 3));
        price_2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                price_2KeyReleased(evt);
            }
        });
        jPanel1.add(price_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 380, 70, 40));

        quantity_2.setBackground(new java.awt.Color(163, 204, 255));
        quantity_2.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        quantity_2.setForeground(new java.awt.Color(255, 255, 255));
        quantity_2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255), 3));
        quantity_2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                quantity_2KeyReleased(evt);
            }
        });
        jPanel1.add(quantity_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 90, 40));

        name.setBackground(new java.awt.Color(153, 204, 255));
        name.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        name.setForeground(new java.awt.Color(255, 255, 255));
        name.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255), 3));
        name.setEnabled(false);
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        jPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 280, 40));

        jPanel3.setBackground(new java.awt.Color(0, 204, 51));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Add");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel6)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 90, 120, 40));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("NAME");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        buy_price_2.setBackground(new java.awt.Color(153, 204, 255));
        buy_price_2.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        buy_price_2.setForeground(new java.awt.Color(255, 255, 255));
        buy_price_2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255), 3));
        buy_price_2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                buy_price_2KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                buy_price_2KeyReleased(evt);
            }
        });
        jPanel1.add(buy_price_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 290, 70, 40));

        jLabel14.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("PRICE");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, 40, 20));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("SELLING PRICE");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 100, -1));

        jLabel15.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Cost per item =");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, 110, 20));

        buy_price2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        buy_price2.setForeground(new java.awt.Color(255, 255, 255));
        buy_price2.setText("0");
        jPanel1.add(buy_price2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 350, 100, 20));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Profit per item =");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, 110, 20));

        profit.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        profit.setForeground(new java.awt.Color(255, 255, 255));
        profit.setText("0");
        jPanel1.add(profit, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 490, 80, 20));

        jPanel7.setBackground(new java.awt.Color(0, 143, 204));
        jPanel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel7MouseClicked(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Transaction");

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images778.png"))); // NOI18N

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 410, 130, 130));

        jPanel8.setBackground(new java.awt.Color(0, 102, 153));
        jPanel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel8MouseClicked(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("New");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel12)
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 160, 120, 40));

        jLabel17.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Avg price/item =");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, 120, 30));

        avg_buy.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        avg_buy.setForeground(new java.awt.Color(255, 255, 255));
        avg_buy.setText("0");
        jPanel1.add(avg_buy, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 450, 100, 30));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Add Product");

        jPanel5.setBackground(new java.awt.Color(0, 153, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTable1MouseReleased(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTable1KeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel4.setBackground(new java.awt.Color(0, 102, 153));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Delete");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 113, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(0, 34, Short.MAX_VALUE)
                    .addComponent(jLabel8)
                    .addGap(0, 34, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(0, 10, Short.MAX_VALUE)
                    .addComponent(jLabel8)
                    .addGap(0, 11, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 655, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("PRODUCTS ON STOCK", jPanel5);

        jPanel6.setBackground(new java.awt.Color(0, 153, 255));

        jPanel9.setBackground(new java.awt.Color(0, 102, 153));
        jPanel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel9MouseClicked(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Delete");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 113, Short.MAX_VALUE)
            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel9Layout.createSequentialGroup()
                    .addGap(0, 34, Short.MAX_VALUE)
                    .addComponent(jLabel13)
                    .addGap(0, 34, Short.MAX_VALUE)))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel9Layout.createSequentialGroup()
                    .addGap(0, 10, Short.MAX_VALUE)
                    .addComponent(jLabel13)
                    .addGap(0, 11, Short.MAX_VALUE)))
        );

        t_sold.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(t_sold);

        sell_date.setDateFormatString("yyyy-MM-dd");

        jButton6.setText("Filter");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(530, Short.MAX_VALUE)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jScrollPane3)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sell_date, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton6)
                    .addComponent(sell_date, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("SOLD PRODUCTS", jPanel6);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(40, 40, 40)))
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 622, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1))
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 555, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1310, 594));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
        // TODO add your handling code here:
        //Connection conn=null;
        Statement stmt=null;
    String name_d=name.getText();
    String detail_d=detail.getText();
    String price_d=price_2.getText();
    String quantity_d=quantity_2.getText();
    String supplier_d=supplier.getText();
        try{
        javaconnect connect=new javaconnect();
          Connection conn=javaconnect.getConnection();
            
            int index=jTable1.getSelectedRow();
      TableModel model=jTable1.getModel();
            String id_e = model.getValueAt(index, 0).toString();
      String name_e = model.getValueAt(index, 1).toString();
      String detail_e = model.getValueAt(index, 2).toString();
      String price_e = model.getValueAt(index, 3).toString();
      String buying_p = model.getValueAt(index, 5).toString();
      String quantity_p = model.getValueAt(index, 4).toString();
      float buying_pc=Float.valueOf(buying_p);
      float quantity_pc=Float.valueOf(quantity_p);
        float q=Integer.parseInt(quantity_2.getText());
      float b=Integer.parseInt(buy_price_2.getText());
    BigDecimal num=new BigDecimal(((buying_pc*quantity_pc)+b)/(quantity_pc+q));
    float fr=Float.valueOf(num.toString());
   // float avg=((buying_pc*quantity_pc)+b)/(quantity_pc+q);
              String f=String.valueOf(fr);
              float qt=quantity_pc+q;
              String qts=String.valueOf(qt);
           String sql="update product set price='"+price_2.getText()+"',quantity='"+qts+"',buying_price='"+f+"',supplier='"+supplier.getText()+"',date_added=CURRENT_TIMESTAMP where id='"+id_e+"'";
            stmt=conn.createStatement();
           stmt.executeUpdate(sql);
           // stmt.setString(1,name_d);
    name.setText("");
    detail.setText("");
    price_2.setText("");
    quantity_2.setText("");
    supplier.setText("");
    profit.setText("0");
    buy_price2.setText("0");
    buy_price_2.setText("");
    ResultSet rs=null;
       // Statement stmt=null;
        PreparedStatement pst=null;

       // rs=pst.executeQuery();
       // jTable1.setModel(DbUtils.resultSetToTableModel(rs));
        String sql2="select  id as 'id',`Date_added` as 'Date added',name as 'Name',detail as 'Description',quantity as 'Quantity',buying_price as 'Buying price',supplier as 'Supplier',price as 'Cost (Ksh)' from product order by date_added desc";
         pst=conn.prepareStatement(sql2);
        rs=pst.executeQuery();
        jTable1.setModel(DbUtils.resultSetToTableModel(rs));
        TableColumnModel tcm=jTable1.getColumnModel();
        tcm.removeColumn(tcm.getColumn(0));
          JOptionPane.showMessageDialog(null,"Product Succefully added");
            //JOptionPane.showMessageDialog(null,name_d+","+detail_d+","+price_d+","+quantity_d+","+profit.getText()+","+supplier_d);
        }catch(Exception e){
        JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jPanel3MouseClicked

    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked
        // TODO add your handling code here:
try{
        int index=jTable1.getSelectedRow();
    TableModel model=jTable1.getModel();
    PreparedStatement pst=null;
    ResultSet rs=null;
            javaconnect connect=new javaconnect();
          Connection conn=javaconnect.getConnection();
             
        String id_c= model.getValueAt(index, 0).toString();
        //JOptionPane.showMessageDialog(null, id_c);
        String sql="delete from product where id='"+id_c+"'";
        pst=conn.prepareStatement(sql);
        pst.executeUpdate();
        String sql2="select  id as 'id',`Date_added` as 'Date added',name as 'Name',detail as 'Description',quantity as 'Quantity',buying_price as 'Buying price',supplier as 'Supplier',price as 'Cost (Ksh)' from product order by date_added desc";
         pst=conn.prepareStatement(sql2);
        rs=pst.executeQuery();
        jTable1.setModel(DbUtils.resultSetToTableModel(rs));
        TableColumnModel tcm=jTable1.getColumnModel();
        tcm.removeColumn(tcm.getColumn(0));
}catch(Exception e){}
    }//GEN-LAST:event_jPanel4MouseClicked

    private void buy_price_2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buy_price_2KeyPressed

           // JOptionPane.showMessageDialog(null,fr); 
        // TODO add your handling code here:
    }//GEN-LAST:event_buy_price_2KeyPressed

    private void buy_price_2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buy_price_2KeyReleased
      float q=Integer.parseInt(quantity_2.getText());
      float b=Integer.parseInt(buy_price_2.getText());
    BigDecimal num=new BigDecimal(b/q);
    float fr=Float.valueOf(num.toString());
      //    float fr2=Math.round((fr)*10000)/10000;
              String f=String.valueOf(fr);
              buy_price2.setText(f);
     float q2=Float.valueOf(buy_price2.getText());
    float b2=Float.valueOf(price_2.getText());
    // int c2;
    BigDecimal num2=new BigDecimal(b2-q2);
   float fr2=Float.valueOf(num2.toString());
 // c=q-b;
 String f2=String.valueOf(fr2);
 profit.setText(f2);
        // TODO add your handling code here:
    }//GEN-LAST:event_buy_price_2KeyReleased

    private void quantity_2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_quantity_2KeyReleased
  float q=Integer.parseInt(quantity_2.getText());
      float b=Integer.parseInt(buy_price_2.getText());
    BigDecimal num=new BigDecimal(b/q);
    float fr=Float.valueOf(num.toString());
      //    float fr2=Math.round((fr)*10000)/10000;
              String f=String.valueOf(fr);
              buy_price2.setText(f);
              
               float q2=Float.valueOf(f);
    float b2=Float.valueOf(price_2.getText());
    // int c2;
    float c;
    c=b2-q2;
    //BigDecimal num2=new BigDecimal(b2-q2);
   float fr2=Float.valueOf(num.toString());
 // c=q-b;
 String f2=String.valueOf(c);
 profit.setText(f2);
 //String price2=f;
        // TODO add your handling code here:
    }//GEN-LAST:event_quantity_2KeyReleased

    private void price_2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_price_2KeyReleased
    float q=Float.valueOf(buy_price2.getText());
    float b=Float.valueOf(price_2.getText());
     int c;
    BigDecimal num=new BigDecimal(b-q);
   float fr=Float.valueOf(num.toString());
 // c=q-b;
 String f=String.valueOf(fr);
 profit.setText(f);
 float q2=Float.valueOf(buy_price2.getText());
    float b2=Float.valueOf(price_2.getText());
    // int c2;
    BigDecimal num2=new BigDecimal(b2-q2);
   float fr2=Float.valueOf(num.toString());
 // c=q-b;
 String f2=String.valueOf(fr2);
 profit.setText(f2);
 //String price2=f;
        // TODO add your handling code here:
    }//GEN-LAST:event_price_2KeyReleased

    private void jTable1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseReleased
        int index=jTable1.getSelectedRow();
        TableModel model=jTable1.getModel();
        String id_e = model.getValueAt(index, 0).toString();
        String name_e = model.getValueAt(index, 2).toString();
        String detail_e = model.getValueAt(index, 3).toString();
        String price_e = model.getValueAt(index, 6).toString();
        String quantity_e = model.getValueAt(index, 4).toString();
        String supplier_e = model.getValueAt(index, 6).toString();
        //pack();

        name.setText(name_e);
        detail.setText(detail_e);
      //  price_2.setText(price_e);
      //  quantity_2.setText(quantity_e);
       supplier.setText(supplier_e);

        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseReleased

    private void jTable1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyReleased
        int index=jTable1.getSelectedRow();
        TableModel model=jTable1.getModel();
        String id_e = model.getValueAt(index, 0).toString();
        String name_e = model.getValueAt(index, 2).toString();
        String detail_e = model.getValueAt(index, 3).toString();
        String price_e = model.getValueAt(index, 6).toString();
        String quantity_e = model.getValueAt(index, 4).toString();
        String supplier_e = model.getValueAt(index, 5).toString();
        // pack();

        name.setText(name_e);
        detail.setText(detail_e);
      //  price_2.setText(price_e);
      //  quantity_2.setText(quantity_e);
       supplier.setText(supplier_e);

        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1KeyReleased

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_searchActionPerformed

    private void searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchKeyReleased
        String types=jComboBox1.getSelectedItem().toString();
        // JOptionPane.showMessageDialog(null,types);

        try{
           javaconnect connect=new javaconnect();
          Connection conn=javaconnect.getConnection();
            //Connection conn=null;
            ResultSet rs=null;
            Statement stmt=null;
            PreparedStatement pst=null;
         
            String sql="select  id as 'id',`Date_added` as 'Date added',name as 'Name',detail as 'Description',quantity as 'Quantity',supplier as 'Supplier',price as 'Cost (Ksh)' from product where "+types+" like '%"+search.getText()+"%'";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
TableColumnModel tcm=jTable1.getColumnModel();
        tcm.removeColumn(tcm.getColumn(0));
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_searchKeyReleased

    private void jComboBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1MouseClicked

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jPanel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel9MouseClicked
try{
        int index= t_sold.getSelectedRow();
    TableModel model= t_sold.getModel();
    PreparedStatement pst=null;
    ResultSet rs=null;
          javaconnect connect=new javaconnect();
          Connection conn=javaconnect.getConnection();
          String id= model.getValueAt(index, 0).toString();   
        String date_sold= model.getValueAt(index, 6).toString();
        String sql="delete from sells where date_sold='"+date_sold+"' && id='"+id+"' ";
        pst=conn.prepareStatement(sql);
        pst.executeUpdate();
        DateFormat dtf=new SimpleDateFormat("yyyy-MM-dd");
       Date date=new Date();
       //java.util.Date date=new java.util.Date();
        dtf.format(date);
        sell_date.setDate(date);
String sql2="select id,name,detail,quantity,total_cost,profit,date_sold,sold_by from sells where date_sold like '%"+dtf.format(date)+"%' order by date_sold desc";
 
        //String sql2="select * from sells";
         pst=conn.prepareStatement(sql2);
        rs=pst.executeQuery();
        t_sold.setModel(DbUtils.resultSetToTableModel(rs));
        TableColumnModel tcm2=t_sold.getColumnModel();
        tcm2.removeColumn(tcm2.getColumn(0));
}catch(Exception e){}
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel9MouseClicked

    private void jPanel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MouseClicked
        transact vw=new transact();
        vw.setVisible(true);
        this.setVisible(false);

        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel7MouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        try{
            ResultSet rs=null;
            Statement stmt=null;
            PreparedStatement pst=null;
            javaconnect connect=new javaconnect();
          Connection conn=javaconnect.getConnection();
            DateFormat dtf=new SimpleDateFormat("yyyy-MM-dd");
            // Date date=new Date();
            dtf.format(sell_date.getDate());
            String sql_ps="select id,name,detail,quantity,total_cost,profit,date_sold,sold_by from sells where date_sold like '%"+dtf.format(sell_date.getDate())+"%' order by date_sold desc";
            pst=conn.prepareStatement(sql_ps);
            rs=pst.executeQuery();
            t_sold.setModel(DbUtils.resultSetToTableModel(rs));
            TableColumnModel tcm2=t_sold.getColumnModel();
            tcm2.removeColumn(tcm2.getColumn(0));
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Enter date to filter");
        }

    }//GEN-LAST:event_jButton6ActionPerformed

    private void jPanel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel8MouseClicked
add_stock ads=new add_stock();
ads.setVisible(true);
this.setVisible(false);

        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel8MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(stock_view4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(stock_view4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(stock_view4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(stock_view4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new stock_view4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel avg_buy;
    private javax.swing.JLabel buy_price2;
    private javax.swing.JTextField buy_price_2;
    private javax.swing.JTextField detail;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField name;
    private javax.swing.JTextField price_2;
    private javax.swing.JLabel profit;
    private javax.swing.JTextField quantity_2;
    private javax.swing.JTextField search;
    private com.toedter.calendar.JDateChooser sell_date;
    private javax.swing.JTextField supplier;
    private javax.swing.JTable t_sold;
    // End of variables declaration//GEN-END:variables
}
